extends SceneTree

## Guard: the shipped game contains no recorded or third-party audio. Every sound
## is generated by project code, including the local engine fallback loop.

const AUDIO_DIR := "res://assets/audio"
const GENERATOR := preload("res://scripts/audio/engine/engine_loop_generator.gd")
const LIBRARY := preload("res://scripts/audio/engine/engine_recipe_library.gd")
const CATALOG := preload("res://data/championship/catalog.gd")


func _initialize() -> void:
	call_deferred("_run_test")


func _run_test() -> void:
	var dir := DirAccess.open(AUDIO_DIR)
	if not _expect(dir != null, "assets/audio should exist"):
		return
	for file_name: String in dir.get_files():
		var lower := file_name.to_lower()
		if lower.ends_with(".ogg") or lower.ends_with(".wav") or lower.ends_with(".mp3"):
			_fail("%s/%s ships recorded audio; every sound must be generated" % [AUDIO_DIR, file_name])
			return
	var stats := CATALOG.create_vehicle_stats("rustbug")
	var recipe := LIBRARY.resolve("rustbug", stats)
	if not _expect(recipe != null and recipe.is_valid(), "the recipe library should resolve a rustbug recipe"):
		return
	var loop := GENERATOR.generate_cached(recipe)
	if not _expect(loop != null and loop is AudioStreamWAV and loop.get_length() > 0.05, "the generated engine fallback loop must be non-empty"):
		return
	print("AUDIO_ASSETS_TEST PASS generated_audio_only")
	quit(0)


func _expect(condition: bool, message: String) -> bool:
	if condition:
		return true
	_fail(message)
	return false


func _fail(message: String) -> void:
	push_error("AUDIO_ASSETS_TEST FAIL: " + message)
	quit(1)
