extends SceneTree

## Every sound effect and the engine voice are generated by project code. The
## only shipped audio asset left is the engine's fallback loop.
const REVIEW_OGG_NAMES: Array[String] = [
	"engine_loop",
]


func _initialize() -> void:
	for sound_name: String in REVIEW_OGG_NAMES:
		var path := "res://assets/audio/%s.ogg" % sound_name
		var stream := load(path) as AudioStreamOggVorbis
		if stream == null or stream.get_length() <= 0.0:
			_fail("%s should load as non-empty OGG audio" % path)
			return
	print("AUDIO_ASSETS_TEST PASS")
	quit(0)


func _fail(message: String) -> void:
	push_error("AUDIO_ASSETS_TEST FAIL: " + message)
	quit(1)
