class_name TrackBuilderCatalog
## Theme layouts, room compositions, prop contracts, and obstacle rosters.
## Construction stays in TrackBuilderCore.

const GENERATED_RULES := preload("res://scripts/race/generated_circuit_rules.gd")
const PROP_SCALE := preload("res://scripts/race/world_prop_scale.gd")
const WORLD_SCALE := TrackSeedGen.WORLD_SCALE
const VEHICLE_WIDTH := 44.0
const OBSTACLE_ROUTE_CLEARANCE := VEHICLE_WIDTH * 0.5 + 8.0


static var GENERATED_OBSTACLE_TYPES := {
	&"kitchen": [
		{"id": &"dropped_strawberry", "asset": "res://assets/textures/imagine/strawberry.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
		{"id": &"biscuit", "asset": "res://assets/textures/tabletop/biscuit.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
	],
	&"workshop": [
		{"id": &"loose_bolt", "asset": "res://assets/textures/imagine/bolt.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
		{"id": &"loose_nut", "asset": "res://assets/textures/imagine/hazard_workshop_socket.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
	],
	&"office": [
		{"id": &"loose_keycap", "asset": "res://assets/textures/imagine/office_keycap.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
		{"id": &"dropped_eraser", "asset": "res://assets/textures/tabletop/eraser.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
		{"id": &"binder_clip", "asset": "res://assets/textures/edge_dressing/office_binder_clip_micro.png", "clearance": OBSTACLE_ROUTE_CLEARANCE, "role": &"permanent_obstacle"},
	],
}


## `visual_role` is the player-facing contract: SOLID stops cars, FLAT is
## drive-over presentation, and MOVING_HAZARD is a colliding hazard (rolling or parked).
## `collision_contract` remains as compatibility metadata for collision audits.
static var SOLID_EDGE_SHAPES := {
	"screw_small.png": &"rect",
	"paperclip_micro.png": &"rect",
	"cork_bump.png": &"circle",
	"kitchen_rice_micro.png": &"circle",
	"kitchen_herb_micro.png": &"circle",
	"kitchen_sugar_micro.png": &"circle",
	"pencil_shaving.png": &"rect",
	"blade_fragment.png": &"rect",
	"staple_bit.png": &"rect",
	"workshop_nail_micro.png": &"rect",
	"workshop_washer_micro.png": &"circle",
	"workshop_bolt_micro.png": &"circle",
	"office_binder_clip_micro.png": &"rect",
	"office_push_pin_micro.png": &"circle",
	"office_pen_cap_micro.png": &"rect",
}

## These are painted/material details, not objects. They must stay Sprite2D
## presentation with no CollisionObject2D ancestor or descendant.
static var FLAT_EDGE_ASSETS := {
	"crumb_micro_01.png": true,
	"crumb_micro_02.png": true,
	"fiber_strand.png": true,
	"droplet_micro.png": true,
	"wood_grain_faint.png": true,
	"sawdust_bit.png": true,
	"desk_pad_grid.png": true,
}


## Exceptions to the broad PROP_SHAPES presentation categories. These assets
## are visibly elongated or rectangular even though older placement data used a
## circle. `no_rotation` also protects axis-aligned art from unstable PCA angles.
static var ASSET_FOOTPRINT_OVERRIDES := {
	"hero_workshop_toolbox.png": {"kind": &"convex", "no_rotation": true},
	"hero_workshop_wrench.png": {"kind": &"convex", "no_rotation": true},
	"hero_workshop_paint_can.png": {"kind": &"convex", "no_rotation": true},
	"hero_office_keyboard.png": {"kind": &"convex", "no_rotation": true},
	"hero_office_notebook.png": {"kind": &"convex", "no_rotation": true},
	"hero_office_keycap.png": {"kind": &"rect", "no_rotation": true},
	"hero_kitchen_mug.png": {"kind": &"convex", "no_rotation": true},
	"hero_kitchen_plate_stack.png": {"kind": &"convex", "no_rotation": true},
	"hero_kitchen_tea_board.png": {"kind": &"convex", "no_rotation": true},
	"watermelon.png": {"kind": &"capsule", "no_rotation": true},
	"giant_watermelon.png": {"kind": &"capsule", "no_rotation": true},
	"giant_mug.png": {"kind": &"convex", "no_rotation": true},
	"giant_basketball.png": {"kind": &"convex", "no_rotation": true},
	"giant_fork.png": {"kind": &"convex", "no_rotation": true},
	"giant_toaster.png": {"kind": &"convex", "no_rotation": true},
	"giant_milk_carton.png": {"kind": &"convex", "no_rotation": true},
	"giant_toolbox.png": {"kind": &"convex", "no_rotation": true},
	"giant_paint_can.png": {"kind": &"convex", "no_rotation": true},
	"giant_keyboard.png": {"kind": &"convex", "no_rotation": true},
	"giant_monitor.png": {"kind": &"convex", "no_rotation": true},
	"giant_paper_stack.png": {"kind": &"convex", "no_rotation": true},
	"giant_pen.png": {"kind": &"convex", "no_rotation": true},
	"giant_hammer.png": {"kind": &"convex", "no_rotation": true},
	"hammer.png": {"kind": &"convex", "no_rotation": true},
	"giant_wrench.png": {"kind": &"convex", "no_rotation": true},
	"giant_stapler.png": {"kind": &"convex", "no_rotation": true},
	"giant_mouse.png": {"kind": &"convex", "no_rotation": true},
	"bucket_stack.png": {"kind": &"convex", "no_rotation": true},
	"monitor_top.png": {"kind": &"convex", "no_rotation": true},
	"mug_top.png": {"kind": &"convex", "no_rotation": true},
	"mug_blue.png": {"kind": &"convex", "no_rotation": true},
	"kitchen_mug_blue.png": {"kind": &"convex", "no_rotation": true},
	"kitchen_mug_hero.png": {"kind": &"convex", "no_rotation": true},
	"cereal_tower_green.png": {"kind": &"rect", "no_rotation": true},
	"kitchen_cereal_green.png": {"kind": &"rect", "no_rotation": true},
	"kitchen_cereal_orange.png": {"kind": &"rect", "no_rotation": true},
	"office_keycap.png": {"kind": &"rect", "no_rotation": true},
	"sponge_wet.png": {"kind": &"rect", "no_rotation": true},
	"kitchen_sponge.png": {"kind": &"rect", "no_rotation": true},
	"napkin.png": {"kind": &"rect", "no_rotation": true},
	"hazard_workshop_socket.png": {"kind": &"convex", "no_rotation": true},

	"workshop_toolbox_top_bright.jpg": {"kind": &"rect", "no_rotation": true},
	"office_keyboard_top_bright.jpg": {"kind": &"rect", "no_rotation": true},
	"stove_top.png": {"kind": &"rect", "no_rotation": true},
}

static var ROOM_SHAPES := {
	"classic": PackedVector2Array([Vector2(-875, -575) * WORLD_SCALE, Vector2(875, -575) * WORLD_SCALE, Vector2(875, 575) * WORLD_SCALE, Vector2(-875, 575) * WORLD_SCALE]),
	"wide": PackedVector2Array([Vector2(-1175, -600) * WORLD_SCALE, Vector2(1175, -600) * WORLD_SCALE, Vector2(1175, 600) * WORLD_SCALE, Vector2(-1175, 600) * WORLD_SCALE]),
	"tall": PackedVector2Array([Vector2(-575, -725) * WORLD_SCALE, Vector2(575, -725) * WORLD_SCALE, Vector2(575, 725) * WORLD_SCALE, Vector2(-575, 725) * WORLD_SCALE]),
	"el": PackedVector2Array([Vector2(-1200, -700) * WORLD_SCALE, Vector2(360, -700) * WORLD_SCALE, Vector2(360, -60) * WORLD_SCALE, Vector2(1200, -60) * WORLD_SCALE, Vector2(1200, 700) * WORLD_SCALE, Vector2(-1200, 700) * WORLD_SCALE]),
	"long": PackedVector2Array([Vector2(-1300, -550) * WORLD_SCALE, Vector2(1300, -550) * WORLD_SCALE, Vector2(1300, 550) * WORLD_SCALE, Vector2(-1300, 550) * WORLD_SCALE]),
	"square": PackedVector2Array([Vector2(-750, -750) * WORLD_SCALE, Vector2(750, -750) * WORLD_SCALE, Vector2(750, 750) * WORLD_SCALE, Vector2(-750, 750) * WORLD_SCALE]),
}

static var BASE_ROOM_SHAPES := {
	"classic": PackedVector2Array([Vector2(-875, -575), Vector2(875, -575), Vector2(875, 575), Vector2(-875, 575)]),
	"wide": PackedVector2Array([Vector2(-1175, -600), Vector2(1175, -600), Vector2(1175, 600), Vector2(-1175, 600)]),
	"tall": PackedVector2Array([Vector2(-575, -725), Vector2(575, -725), Vector2(575, 725), Vector2(-575, 725)]),
	"el": PackedVector2Array([Vector2(-1200, -700), Vector2(360, -700), Vector2(360, -60), Vector2(1200, -60), Vector2(1200, 700), Vector2(-1200, 700)]),
	"long": PackedVector2Array([Vector2(-1300, -550), Vector2(1300, -550), Vector2(1300, 550), Vector2(-1300, 550)]),
	"square": PackedVector2Array([Vector2(-750, -750), Vector2(750, -750), Vector2(750, 750), Vector2(-750, 750)]),
}

static var ISLAND_VIGNETTES := {
	&"kitchen": [
		[
			{"tex": "res://assets/textures/imagine/teapot_top.png", "pos": Vector2(-0.15, -0.25), "rot": 0.2},
			{"tex": "res://assets/textures/imagine/mug_top.png", "pos": Vector2(0.35, -0.3), "rot": -0.4},
			{"tex": "res://assets/textures/kitchen/mug_blue.png", "pos": Vector2(0.55, -0.15), "rot": 0.9},
			{"tex": "res://assets/textures/imagine/plate_stack.png", "pos": Vector2(-0.45, 0.3), "rot": 0.05},
			{"tex": "res://assets/textures/kitchen/fork_cartoon.png", "pos": Vector2(-0.28, 0.42), "rot": -0.6},
			{"tex": "res://assets/textures/kitchen/spoon_bridge.png", "pos": Vector2(-0.1, 0.48), "rot": -0.5},
			{"tex": "res://assets/textures/imagine/teacup_saucer.png", "pos": Vector2(0.15, -0.45), "rot": 0.3},
			{"tex": "res://assets/textures/imagine/salt_shaker.png", "pos": Vector2(0.5, 0.35), "rot": 0.1},
			{"tex": "res://assets/textures/imagine/crumb_cluster.png", "pos": Vector2(-0.3, 0.05), "rot": 0.0, "decal": true},
			{"tex": "res://assets/textures/imagine/stain_ring.png", "pos": Vector2(0.35, -0.1), "rot": 0.0, "decal": true},
		],
		[
			{"tex": "res://assets/textures/imagine/watermelon.png", "pos": Vector2(0.1, 0.2), "rot": 0.4},
			{"tex": "res://assets/textures/imagine/vase_top.png", "pos": Vector2(-0.4, -0.25), "rot": 0.0},
			{"tex": "res://assets/textures/kitchen/mug_hero.png", "pos": Vector2(0.5, -0.3), "rot": -0.2},
			{"tex": "res://assets/textures/imagine/plate_stack.png", "pos": Vector2(-0.15, 0.35), "rot": -0.1},
			{"tex": "res://assets/textures/kitchen/spoon_bridge.png", "pos": Vector2(-0.05, 0.45), "rot": -0.8},
			{"tex": "res://assets/textures/imagine/teacup_saucer.png", "pos": Vector2(0.55, 0.15), "rot": 0.6},
			{"tex": "res://assets/textures/imagine/crumb_cluster.png", "pos": Vector2(0.2, -0.4), "rot": 0.0, "decal": true},
			{"tex": "res://assets/textures/imagine/stain_ring.png", "pos": Vector2(-0.45, 0.15), "rot": 0.0, "decal": true},
		],
	],
	&"workshop": [
		[
			{"tex": "res://assets/textures/imagine/barrel_wood.png", "pos": Vector2(0.25, 0.15), "rot": 0.1},
			{"tex": "res://assets/textures/imagine/workshop_paint_can.png", "pos": Vector2(-0.4, -0.2), "rot": -0.3},
			{"tex": "res://assets/textures/imagine/workshop_paint_can.png", "pos": Vector2(-0.25, -0.4), "rot": 0.5},
			{"tex": "res://assets/textures/imagine/hose_coil.png", "pos": Vector2(-0.35, 0.35), "rot": -0.2},
			{"tex": "res://assets/textures/imagine/wrench.png", "pos": Vector2(0.5, -0.35), "rot": 1.2},
			{"tex": "res://assets/textures/imagine/hammer.png", "pos": Vector2(0.15, -0.45), "rot": -1.0},
			{"tex": "res://assets/textures/imagine/screwdriver.png", "pos": Vector2(0.55, 0.05), "rot": -0.7},
			{"tex": "res://assets/textures/imagine/sawdust_patch.png", "pos": Vector2(-0.05, 0.05), "rot": 0.0, "decal": true},
			{"tex": "res://assets/textures/imagine/oil_stain.png", "pos": Vector2(0.4, 0.4), "rot": 0.0, "decal": true},
		],
		[
			{"tex": "res://assets/textures/imagine/teapot_top.png", "pos": Vector2(-0.3, -0.15), "rot": 0.0},
			{"tex": "res://assets/textures/imagine/flower_pot.png", "pos": Vector2(0.45, -0.25), "rot": 0.2},
			{"tex": "res://assets/textures/imagine/basketball.png", "pos": Vector2(0.15, 0.4), "rot": 0.0},
			{"tex": "res://assets/textures/imagine/workshop_paint_can.png", "pos": Vector2(-0.5, 0.25), "rot": 0.4},
			{"tex": "res://assets/textures/imagine/hammer.png", "pos": Vector2(0.0, -0.45), "rot": 1.4},
			{"tex": "res://assets/textures/imagine/screwdriver.png", "pos": Vector2(0.55, 0.3), "rot": -0.4},
			{"tex": "res://assets/textures/imagine/sawdust_patch.png", "pos": Vector2(0.2, -0.15), "rot": 0.0, "decal": true},
			{"tex": "res://assets/textures/imagine/oil_stain.png", "pos": Vector2(-0.15, 0.3), "rot": 0.0, "decal": true},
		],
	],
	&"office": [
		[
			{"tex": "res://assets/textures/imagine/lamp_desk.png", "pos": Vector2(-0.35, -0.3), "rot": 0.0},
			{"tex": "res://assets/textures/imagine/mug_top.png", "pos": Vector2(0.3, -0.4), "rot": 0.4},
			{"tex": "res://assets/textures/imagine/book_top.png", "pos": Vector2(0.5, 0.2), "rot": -0.3},
			{"tex": "res://assets/textures/imagine/remote_control.png", "pos": Vector2(-0.15, 0.45), "rot": 0.15},
			{"tex": "res://assets/textures/imagine/pencil.png", "pos": Vector2(0.05, -0.2), "rot": -0.9},
			{"tex": "res://assets/textures/imagine/stapler_top.png", "pos": Vector2(-0.5, 0.05), "rot": 0.6},
			{"tex": "res://assets/textures/imagine/paper_sheet.png", "pos": Vector2(0.1, 0.15), "rot": 0.1, "decal": true},
			{"tex": "res://assets/textures/imagine/stain_ring.png", "pos": Vector2(0.35, 0.35), "rot": 0.0, "decal": true},
		],
		[
			{"tex": "res://assets/textures/imagine/tape_roll.png", "pos": Vector2(0.45, -0.3), "rot": 0.3},
			{"tex": "res://assets/textures/imagine/plate_stack.png", "pos": Vector2(-0.35, 0.3), "rot": 0.0},
			{"tex": "res://assets/textures/imagine/bottle_top.png", "pos": Vector2(-0.15, -0.4), "rot": 0.0},
			{"tex": "res://assets/textures/imagine/mug_top.png", "pos": Vector2(0.2, 0.4), "rot": -0.3},
			{"tex": "res://assets/textures/imagine/scissors_top.png", "pos": Vector2(0.55, 0.1), "rot": 0.9},
			{"tex": "res://assets/textures/imagine/pencil.png", "pos": Vector2(-0.5, -0.1), "rot": 0.5},
			{"tex": "res://assets/textures/imagine/paper_sheet.png", "pos": Vector2(-0.1, 0.05), "rot": -0.15, "decal": true},
			{"tex": "res://assets/textures/imagine/stain_ring.png", "pos": Vector2(0.4, -0.05), "rot": 0.0, "decal": true},
		],
	],
}


## Generated tracks use one complete room composition. Unlike the legacy static-track
## pools below, every asset in a composition belongs to the same household story.
## Internal name was STORY_KITS; that alias remains for existing tests.
static var ROOM_COMPOSITIONS := {
	&"kitchen": [
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["kitchen"][0]),
			"giants": ["res://assets/textures/kitchen_hero/hero_kitchen_plate_stack.png", "res://assets/textures/giant_props/giant_milk_carton.png", "res://assets/textures/giant_props/giant_cereal_box.png"],
			"island": [
				{"asset": "res://assets/textures/giant_props/giant_toaster.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8)},
				{"asset": "res://assets/textures/imagine/teacup_saucer.png", "assets": ["res://assets/textures/imagine/teacup_saucer.png", "res://assets/textures/tabletop/mug_patterned.png", "res://assets/textures/tabletop/mug_enamel_red.png"], "quantity": &"few", "count": 3, "formation": &"arc", "offset": Vector2(66, -12)},
				{"asset": "res://assets/textures/tabletop/cereal_ring.png", "assets": ["res://assets/textures/tabletop/cereal_ring.png", "res://assets/textures/tabletop/biscuit_round.png", "res://assets/textures/tabletop/cracker_square.png"], "quantity": &"many", "count": 10, "formation": &"cluster", "offset": Vector2(16, 78)},
			],
			"object_line": {"asset": "res://assets/textures/tabletop/biscuit.png", "assets": ["res://assets/textures/tabletop/biscuit.png", "res://assets/textures/tabletop/biscuit_round.png", "res://assets/textures/tabletop/cracker_square.png"], "count": 10},
			"delimiter": {"asset": "res://assets/textures/imagine/kitchen_spoon.png", "assets": ["res://assets/textures/imagine/kitchen_spoon.png", "res://assets/textures/tabletop/teaspoon.png", "res://assets/textures/tabletop/dessert_spoon.png"], "count": 2},
			"landmarks": ["res://assets/textures/kitchen_hero/hero_kitchen_mug.png", "res://assets/textures/kitchen_hero/hero_kitchen_plate_stack.png"],
			"surfaces": [
				{"name": &"breakfast crumbs", "grip": 0.82, "speed": 0.76, "decal": "res://assets/textures/imagine/crumb_cluster.png"},
				{"name": &"tea spill", "grip": 0.56, "speed": 0.88, "decal": "res://assets/textures/kitchen/wet_spill.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["kitchen"][1]),
			"island": [
				{"asset": "res://assets/textures/kitchen/cutting_board.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-28, 0)},
				{"asset": "res://assets/textures/imagine/frying_pan.png", "quantity": &"few", "count": 2, "formation": &"arc", "offset": Vector2(70, -22)},
				{"asset": "res://assets/textures/kitchen/lime_cartoon.png", "assets": ["res://assets/textures/kitchen/lime_cartoon.png", "res://assets/textures/kitchen/apple_cartoon.png", "res://assets/textures/imagine/strawberry.png"], "quantity": &"many", "count": 12, "formation": &"cluster", "offset": Vector2(12, 78)},
			],
			"object_line": {"asset": "res://assets/textures/kitchen/apple_cartoon.png", "assets": ["res://assets/textures/kitchen/apple_cartoon.png", "res://assets/textures/kitchen/lime_cartoon.png", "res://assets/textures/imagine/strawberry.png"], "count": 12},
			"delimiter": {"asset": "res://assets/textures/imagine/kitchen_fork.png", "assets": ["res://assets/textures/imagine/kitchen_fork.png", "res://assets/textures/tabletop/dinner_fork.png", "res://assets/textures/tabletop/pastry_fork.png"], "count": 2},
			"landmarks": ["res://assets/textures/giant_props/giant_toaster.png", "res://assets/textures/imagine/watermelon.png"],
			"surfaces": [
				{"name": &"prep crumbs", "grip": 0.8, "speed": 0.74, "decal": "res://assets/textures/kitchen/crumb_cluster_02.png"},
				{"name": &"chopping spill", "grip": 0.6, "speed": 0.86, "decal": "res://assets/textures/kitchen/spill_decal.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["kitchen"][2]),
			"opening_asset": "res://assets/textures/kitchen_hero/hero_kitchen_mug.png",
			"giants": ["res://assets/textures/kitchen_hero/hero_kitchen_plate_stack.png"],
			"island": [
				{"asset": "res://assets/textures/kitchen_hero/hero_kitchen_tea_board.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-30, -8), "max_radius": 210.0},
				{"asset": "res://assets/textures/kitchen_hero/hero_kitchen_mug.png", "assets": ["res://assets/textures/kitchen_hero/hero_kitchen_mug.png", "res://assets/textures/tabletop/mug_patterned.png", "res://assets/textures/tabletop/mug_enamel_red.png"], "quantity": &"few", "count": 3, "formation": &"arc", "offset": Vector2(66, -6), "max_radius": 72.0},
				{"asset": "res://assets/textures/imagine/strawberry.png", "assets": ["res://assets/textures/imagine/strawberry.png", "res://assets/textures/kitchen/lime_cartoon.png", "res://assets/textures/kitchen/apple_cartoon.png"], "quantity": &"many", "count": 14, "formation": &"arc", "offset": Vector2(4, 74)},
			],
			"object_line": {"asset": "res://assets/textures/tabletop/biscuit.png", "assets": ["res://assets/textures/tabletop/biscuit.png", "res://assets/textures/tabletop/biscuit_round.png", "res://assets/textures/tabletop/cracker_square.png"], "count": 10},
			"delimiter": {"asset": "res://assets/textures/imagine/kitchen_fork.png", "assets": ["res://assets/textures/imagine/kitchen_fork.png", "res://assets/textures/tabletop/pastry_fork.png", "res://assets/textures/track_boundary/kitchen_butter_knife.png"], "count": 2},
			"landmarks": ["res://assets/textures/kitchen_hero/hero_kitchen_mug.png", "res://assets/textures/kitchen_hero/hero_kitchen_plate_stack.png"],
			"surfaces": [
				{"name": &"tea biscuits", "grip": 0.84, "speed": 0.78, "decal": "res://assets/textures/imagine/crumb_cluster.png"},
				{"name": &"saucer spill", "grip": 0.54, "speed": 0.9, "decal": "res://assets/textures/kitchen/wet_spill.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["kitchen"][3]),
			"giants": ["res://assets/textures/giant_props/giant_milk_carton.png", "res://assets/textures/giant_props/giant_fork.png"],
			"island": [
				{"asset": "res://assets/textures/kitchen_hero/hero_kitchen_plate_stack.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 160.0},
				{"asset": "res://assets/textures/kitchen/sponge_wet.png", "quantity": &"few", "count": 3, "formation": &"line", "offset": Vector2(62, -12)},
				{"asset": "res://assets/textures/tabletop/cork.png", "assets": ["res://assets/textures/tabletop/cork.png", "res://assets/textures/tabletop/cork_cylinder.png", "res://assets/textures/tabletop/cork_disk.png"], "quantity": &"many", "count": 8, "formation": &"cluster", "offset": Vector2(8, 78)},
			],
			"object_line": {"asset": "res://assets/textures/tabletop/cork.png", "assets": ["res://assets/textures/tabletop/cork.png", "res://assets/textures/tabletop/cork_cylinder.png", "res://assets/textures/tabletop/cork_disk.png"], "count": 10},
			"delimiter": {"asset": "res://assets/textures/kitchen/napkin.png", "assets": ["res://assets/textures/kitchen/napkin.png", "res://assets/textures/track_boundary/kitchen_craft_stick.png", "res://assets/textures/track_boundary/kitchen_butter_knife.png"], "count": 2},
			"landmarks": ["res://assets/textures/giant_props/giant_toaster.png", "res://assets/textures/imagine/teapot_top.png"],
			"surfaces": [
				{"name": &"cleanup suds", "grip": 0.62, "speed": 0.82, "decal": "res://assets/textures/kitchen/spill_decal.png"},
				{"name": &"wipe crumbs", "grip": 0.86, "speed": 0.8, "decal": "res://assets/textures/kitchen/crumb_cluster_01.png"},
			],
		},
	],
	&"workshop": [
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["workshop"][0]),
			"island": [
				{"asset": "res://assets/textures/workshop_hero/hero_workshop_toolbox.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 120.0},
				{"asset": "res://assets/textures/imagine/hammer.png", "assets": ["res://assets/textures/imagine/hammer.png", "res://assets/textures/imagine/wrench.png", "res://assets/textures/imagine/screwdriver.png"], "quantity": &"few", "count": 2, "formation": &"line", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/imagine/screw.png", "assets": ["res://assets/textures/imagine/screw.png", "res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png"], "quantity": &"many", "count": 16, "formation": &"cluster", "offset": Vector2(8, 76)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/screw.png", "assets": ["res://assets/textures/imagine/screw.png", "res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png"], "count": 16},
			"delimiter": {"asset": "res://assets/textures/imagine/plank_wood.png", "assets": ["res://assets/textures/imagine/plank_wood.png", "res://assets/textures/track_boundary/workshop_paint_stirrer_rail.png", "res://assets/textures/track_boundary/workshop_dowel_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/imagine/bucket_stack.png", "res://assets/textures/imagine/barrel_wood.png"],
			"surfaces": [
				{"name": &"carpentry sawdust", "grip": 0.76, "speed": 0.7, "decal": "res://assets/textures/imagine/sawdust_patch.png"},
				{"name": &"bench oil", "grip": 0.46, "speed": 0.9, "decal": "res://assets/textures/imagine/oil_stain.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["workshop"][1]),
			"island": [
				{"asset": "res://assets/textures/workshop_hero/hero_workshop_paint_can.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 120.0},
				{"asset": "res://assets/textures/imagine/workshop_paint_can.png", "quantity": &"few", "count": 3, "formation": &"arc", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/imagine/bolt.png", "assets": ["res://assets/textures/imagine/bolt.png", "res://assets/textures/imagine/screw.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png"], "quantity": &"many", "count": 12, "formation": &"arc", "offset": Vector2(4, 78)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/bolt.png", "assets": ["res://assets/textures/imagine/bolt.png", "res://assets/textures/imagine/screw.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png"], "count": 14},
			"delimiter": {"asset": "res://assets/textures/imagine/plank_wood.png", "assets": ["res://assets/textures/imagine/plank_wood.png", "res://assets/textures/track_boundary/workshop_clamp_rail.png", "res://assets/textures/track_boundary/workshop_ruler_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/workshop_hero/hero_workshop_wrench.png", "res://assets/textures/imagine/hose_coil.png"],
			"surfaces": [
				{"name": &"paint dust", "grip": 0.74, "speed": 0.72, "decal": "res://assets/textures/imagine/sawdust_patch.png"},
				{"name": &"paint station oil", "grip": 0.44, "speed": 0.88, "decal": "res://assets/textures/imagine/oil_stain.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["workshop"][2]),
			"island": [
				{"asset": "res://assets/textures/workshop_hero/hero_workshop_toolbox.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 120.0},
				{"asset": "res://assets/textures/workshop_hero/hero_workshop_wrench.png", "assets": ["res://assets/textures/workshop_hero/hero_workshop_wrench.png", "res://assets/textures/imagine/hammer.png", "res://assets/textures/imagine/screwdriver.png"], "quantity": &"few", "count": 3, "formation": &"arc", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/imagine/screw.png", "assets": ["res://assets/textures/imagine/screw.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/edge_dressing/blade_fragment.png"], "quantity": &"many", "count": 14, "formation": &"cluster", "offset": Vector2(4, 78)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/screw.png", "assets": ["res://assets/textures/imagine/screw.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/edge_dressing/blade_fragment.png"], "count": 14},
			"delimiter": {"asset": "res://assets/textures/imagine/plank_wood.png", "assets": ["res://assets/textures/imagine/plank_wood.png", "res://assets/textures/track_boundary/workshop_ruler_rail.png", "res://assets/textures/track_boundary/workshop_paint_stirrer_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/imagine/bucket_stack.png", "res://assets/textures/imagine/hose_coil.png"],
			"surfaces": [
				{"name": &"repair oil", "grip": 0.43, "speed": 0.9, "decal": "res://assets/textures/imagine/oil_stain.png"},
				{"name": &"repair sawdust", "grip": 0.78, "speed": 0.7, "decal": "res://assets/textures/imagine/sawdust_patch.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["workshop"][3]),
			"island": [
				{"asset": "res://assets/textures/imagine/hose_coil.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8)},
				{"asset": "res://assets/textures/imagine/bucket_stack.png", "quantity": &"few", "count": 2, "formation": &"arc", "offset": Vector2(72, -8)},
				{"asset": "res://assets/textures/imagine/bolt.png", "assets": ["res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png", "res://assets/textures/imagine/hazard_workshop_socket.png"], "quantity": &"many", "count": 10, "formation": &"cluster", "offset": Vector2(4, 80)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/bolt.png", "assets": ["res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png", "res://assets/textures/imagine/hazard_workshop_socket.png"], "count": 12},
			"delimiter": {"asset": "res://assets/textures/imagine/plank_wood.png", "assets": ["res://assets/textures/imagine/plank_wood.png", "res://assets/textures/track_boundary/workshop_dowel_rail.png", "res://assets/textures/track_boundary/workshop_clamp_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/imagine/barrel_wood.png", "res://assets/textures/workshop_hero/hero_workshop_paint_can.png"],
			"surfaces": [
				{"name": &"garage oil", "grip": 0.42, "speed": 0.88, "decal": "res://assets/textures/imagine/oil_stain.png"},
				{"name": &"garage dust", "grip": 0.75, "speed": 0.68, "decal": "res://assets/textures/imagine/sawdust_patch.png"},
			],
		},
	],
	&"office": [
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["office"][0]),
			"opening_asset": "res://assets/textures/office_hero/hero_office_notebook.png",
			"island": [
				{"asset": "res://assets/textures/office_hero/hero_office_keyboard.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 210.0},
				{"asset": "res://assets/textures/office_hero/hero_office_keycap.png", "assets": ["res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/tabletop/eraser.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png"], "quantity": &"few", "count": 2, "formation": &"line", "offset": Vector2(72, -8)},
				{"asset": "res://assets/textures/imagine/paperclip.png", "assets": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png", "res://assets/textures/edge_dressing/office_push_pin_micro.png", "res://assets/textures/edge_dressing/staple_bit.png"], "quantity": &"many", "count": 16, "formation": &"cluster", "offset": Vector2(4, 78)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/paperclip.png", "assets": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png", "res://assets/textures/edge_dressing/office_push_pin_micro.png", "res://assets/textures/edge_dressing/staple_bit.png"], "count": 16},
			"delimiter": {"asset": "res://assets/textures/imagine/remote_control.png", "assets": ["res://assets/textures/imagine/remote_control.png", "res://assets/textures/imagine/pencil.png", "res://assets/textures/track_boundary/office_pen_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/imagine/lamp_desk.png", "res://assets/textures/office_hero/hero_office_notebook.png"],
			"surfaces": [
				{"name": &"workstation papers", "grip": 0.82, "speed": 0.76, "decal": "res://assets/textures/imagine/paper_sheet.png"},
				{"name": &"workstation coffee", "grip": 0.6, "speed": 0.86, "decal": "res://assets/textures/imagine/stain_ring.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["office"][1]),
			"island": [
				{"asset": "res://assets/textures/office_hero/hero_office_notebook.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8), "max_radius": 140.0},
				{"asset": "res://assets/textures/imagine/stapler_top.png", "assets": ["res://assets/textures/imagine/stapler_top.png", "res://assets/textures/imagine/tape_roll.png", "res://assets/textures/imagine/pencil.png"], "quantity": &"few", "count": 3, "formation": &"arc", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/imagine/paperclip.png", "assets": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/tabletop/eraser.png"], "quantity": &"many", "count": 14, "formation": &"cluster", "offset": Vector2(4, 78)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/paperclip.png", "assets": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/tabletop/eraser.png"], "count": 14},
			"delimiter": {"asset": "res://assets/textures/imagine/tape_roll.png", "assets": ["res://assets/textures/imagine/tape_roll.png", "res://assets/textures/track_boundary/office_ruler_rail.png", "res://assets/textures/track_boundary/office_book_spine_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/imagine/monitor_top.png", "res://assets/textures/imagine/tape_roll.png"],
			"surfaces": [
				{"name": &"mail papers", "grip": 0.8, "speed": 0.74, "decal": "res://assets/textures/imagine/paper_sheet.png"},
				{"name": &"mailroom coffee", "grip": 0.58, "speed": 0.86, "decal": "res://assets/textures/imagine/stain_ring.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["office"][2]),
			"opening_asset": "res://assets/textures/office_hero/hero_office_notebook.png",
			"island": [
				{"asset": "res://assets/textures/imagine/crayons.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8)},
				{"asset": "res://assets/textures/imagine/scissors_top.png", "quantity": &"few", "count": 2, "formation": &"arc", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/tabletop/eraser.png", "assets": ["res://assets/textures/tabletop/eraser.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/edge_dressing/office_pen_cap_micro.png"], "quantity": &"many", "count": 10, "formation": &"arc", "offset": Vector2(4, 80)},
			],
			"object_line": {"asset": "res://assets/textures/edge_dressing/pencil_shaving.png", "assets": ["res://assets/textures/edge_dressing/pencil_shaving.png", "res://assets/textures/edge_dressing/office_pen_cap_micro.png", "res://assets/textures/edge_dressing/office_push_pin_micro.png"], "count": 10},
			"delimiter": {"asset": "res://assets/textures/imagine/stapler_top.png", "assets": ["res://assets/textures/imagine/stapler_top.png", "res://assets/textures/imagine/pencil.png", "res://assets/textures/track_boundary/office_pen_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/office_hero/hero_office_notebook.png", "res://assets/textures/imagine/lamp_desk.png"],
			"surfaces": [
				{"name": &"sketch papers", "grip": 0.83, "speed": 0.75, "decal": "res://assets/textures/imagine/paper_sheet.png"},
				{"name": &"sketch coffee", "grip": 0.61, "speed": 0.85, "decal": "res://assets/textures/imagine/stain_ring.png"},
			],
		},
		{
			"id": StringName(GENERATED_RULES.STORY_IDS["office"][3]),
			"opening_asset": "res://assets/textures/office_hero/hero_office_notebook.png",
			"island": [
				{"asset": "res://assets/textures/kitchen_hero/hero_kitchen_mug.png", "quantity": &"unique", "count": 1, "formation": &"focal", "offset": Vector2(-34, -8)},
				{"asset": "res://assets/textures/imagine/book_top.png", "quantity": &"few", "count": 2, "formation": &"line", "offset": Vector2(70, -8)},
				{"asset": "res://assets/textures/office_hero/hero_office_keycap.png", "assets": ["res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/imagine/paperclip.png", "res://assets/textures/edge_dressing/office_pen_cap_micro.png"], "quantity": &"many", "count": 12, "formation": &"cluster", "offset": Vector2(4, 78)},
			],
			"object_line": {"asset": "res://assets/textures/imagine/paperclip.png", "assets": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/edge_dressing/office_pen_cap_micro.png"], "count": 12},
			"delimiter": {"asset": "res://assets/textures/imagine/pencil.png", "assets": ["res://assets/textures/imagine/pencil.png", "res://assets/textures/track_boundary/office_ruler_rail.png", "res://assets/textures/track_boundary/office_pen_rail.png"], "count": 2},
			"landmarks": ["res://assets/textures/office_hero/hero_office_notebook.png", "res://assets/textures/imagine/lamp_desk.png"],
			"surfaces": [
				{"name": &"coffee papers", "grip": 0.81, "speed": 0.75, "decal": "res://assets/textures/imagine/paper_sheet.png"},
				{"name": &"coffee ring", "grip": 0.55, "speed": 0.84, "decal": "res://assets/textures/imagine/stain_ring.png"},
			],
		},
	],
}
static var STORY_KITS := ROOM_COMPOSITIONS


static var PROP_SHAPES := {
	"hero_workshop_toolbox.png": {"solid": true, "shape": "rect", "size": Vector2(240.0, 240.0), "large_focal": true, "giant_max_size": 340.0},
	"hero_workshop_wrench.png": {"solid": true, "shape": "rect", "size": Vector2(24.0, 80.0)},
	"hero_workshop_paint_can.png": {"solid": true, "shape": "circle", "shadow_shape": &"circle", "size": Vector2(240.0, 240.0), "large_focal": true, "giant_max_size": 360.0},
	"hero_office_keyboard.png": {"solid": true, "shape": "rect", "size": Vector2(420.0, 252.0), "large_focal": true, "giant_max_size": 480.0},
	"hero_office_keycap.png": {"solid": true, "shape": "rect", "size": Vector2(24.0, 24.0)},
	"hero_office_notebook.png": {"solid": true, "shape": "rect", "size": Vector2(180.0, 280.0), "large_focal": true, "giant_max_size": 400.0},
	"hero_kitchen_mug.png": {"solid": true, "shape": "circle", "shadow_shape": &"circle", "size": Vector2(144.0, 144.0)},
	"hero_kitchen_plate_stack.png": {"solid": true, "shape": "circle", "shadow_shape": &"circle", "size": Vector2(320.0, 320.0), "large_focal": true, "giant_max_size": 360.0},
	"hero_kitchen_tea_board.png": {"solid": true, "shape": "rect", "size": Vector2(420.0, 420.0), "large_focal": true},
	"ruler_plank.png": {"shape": "rect", "size": Vector2(110.0, 34.0)},
	"kitchen_ruler.png": {"shape": "rect", "size": Vector2(110.0, 34.0)},
	"plank_wood.png": {"shape": "rect", "size": Vector2(100.0, 38.0)},
	"book_top.png": {"shape": "rect", "size": Vector2(84.0, 62.0)},
	"remote_control.png": {"shape": "rect", "size": Vector2(76.0, 42.0)},

	"hazard_workshop_socket.png": {"shape": "rect", "size": Vector2(96.0, 26.0)},
	"cutting_board.png": {"shape": "rect", "size": Vector2(96.0, 60.0)},
	"screwdriver.png": {"shape": "rect", "size": Vector2(56.0, 20.0)},
	"stapler_top.png": {"shape": "rect", "size": Vector2(60.0, 32.0)},
	"pencil.png": {"shape": "rect", "size": Vector2(52.0, 16.0)},
	"crayons.png": {"shape": "rect", "size": Vector2(44.0, 28.0)},
	"scissors_top.png": {"shape": "rect", "size": Vector2(52.0, 36.0)},
	"matchbox.png": {"shape": "rect", "size": Vector2(36.0, 26.0)},
	"fork_cartoon.png": {"shape": "rect", "size": Vector2(44.0, 14.0)},
	"kitchen_fork.png": {"shape": "rect", "size": Vector2(44.0, 14.0)},
	"spoon_bridge.png": {"shape": "rect", "size": Vector2(40.0, 13.0)},
	"kitchen_spoon.png": {"shape": "rect", "size": Vector2(40.0, 13.0)},
	"frying_pan.png": {"shape": "circle", "size": Vector2(74.0, 74.0)},
	"barrel_wood.png": {"shape": "circle", "size": Vector2(140.0, 140.0)},
	"flower_pot.png": {"shape": "circle", "size": Vector2(98.0, 98.0)},
	"basketball.png": {"shape": "circle", "size": Vector2(112.0, 112.0)},
	"soccer_ball.png": {"shape": "circle", "size": Vector2(92.0, 92.0)},
	"football.png": {"shape": "circle", "size": Vector2(96.0, 96.0)},
	"watermelon.png": {"shape": "circle", "size": Vector2(102.0, 102.0)},
	"hose_coil.png": {"shape": "circle", "size": Vector2(122.0, 122.0)},
	"teapot_top.png": {"shape": "circle", "size": Vector2(96.0, 96.0)},
	"mug_top.png": {"shape": "circle", "size": Vector2(44.0, 44.0)},
	"bottle_top.png": {"shape": "circle", "size": Vector2(42.0, 42.0)},
	"plate_stack.png": {"shape": "circle", "size": Vector2(64.0, 64.0)},
	"vase_top.png": {"shape": "circle", "size": Vector2(56.0, 56.0)},
	"lamp_desk.png": {"shape": "circle", "size": Vector2(58.0, 58.0)},
	"plant_small.png": {"shape": "circle", "size": Vector2(56.0, 56.0)},
	"tape_roll.png": {"shape": "circle", "size": Vector2(40.0, 40.0)},
	"teacup_saucer.png": {"shape": "circle", "size": Vector2(46.0, 46.0)},
	"salt_shaker.png": {"shape": "circle", "size": Vector2(30.0, 30.0)},
	"cup_cartoon.png": {"shape": "circle", "size": Vector2(36.0, 36.0)},
	"kitchen_cup.png": {"shape": "circle", "size": Vector2(36.0, 36.0)},
	"mug_blue.png": {"shape": "circle", "size": Vector2(44.0, 44.0)},
	"kitchen_mug_blue.png": {"shape": "circle", "size": Vector2(44.0, 44.0)},
	"kitchen_mug_hero.png": {"shape": "circle", "size": Vector2(44.0, 44.0)},
	"cereal_tower_green.png": {"shape": "circle", "size": Vector2(48.0, 48.0)},
	"kitchen_cereal_green.png": {"shape": "circle", "size": Vector2(48.0, 48.0)},
	"kitchen_cereal_orange.png": {"shape": "circle", "size": Vector2(48.0, 48.0)},
	"apple_cartoon.png": {"shape": "circle", "size": Vector2(28.0, 28.0)},
	"hazard_kitchen_apple.png": {"shape": "circle", "size": Vector2(28.0, 28.0)},
	"lime_cartoon.png": {"shape": "circle", "size": Vector2(26.0, 26.0)},
	"kitchen_lime.png": {"shape": "circle", "size": Vector2(26.0, 26.0)},
	"strawberry.png": {"shape": "circle", "size": Vector2(20.0, 20.0)},
	"bolt.png": {"shape": "circle", "size": Vector2(22.0, 22.0)},
	"screw.png": {"shape": "circle", "size": Vector2(16.0, 16.0)},
	"coin.png": {"shape": "circle", "size": Vector2(12.0, 12.0)},
	"paperclip.png": {"shape": "circle", "size": Vector2(14.0, 14.0)},
	"office_keycap.png": {"shape": "circle", "size": Vector2(32.0, 32.0)},
	"keys_ring.png": {"shape": "circle", "size": Vector2(24.0, 24.0)},
	"napkin.png": {"shape": "circle", "size": Vector2(38.0, 38.0)},
	"sponge_wet.png": {"shape": "circle", "size": Vector2(40.0, 40.0)},
	"kitchen_sponge.png": {"shape": "circle", "size": Vector2(40.0, 40.0)},
	"wrench.png": {"shape": "rect", "size": Vector2(48.0, 20.0)},
	"hammer.png": {"shape": "rect", "size": Vector2(50.0, 24.0)},
	"workshop_paint_can.png": {"shape": "circle", "size": Vector2(52.0, 52.0)},
	"island_tool_tray.png": {"shape": "rect", "size": Vector2(150.0, 150.0)},
	"island_keyboard.png": {"shape": "rect", "size": Vector2(150.0, 150.0)},
	"workshop_toolbox_top_bright.jpg": {"shape": "circle", "size": Vector2(130.0, 130.0)},
	"office_keyboard_top_bright.jpg": {"shape": "circle", "size": Vector2(130.0, 130.0)},
	"plate_large.png": {"shape": "circle", "size": Vector2(130.0, 130.0)},
	"stove_top.png": {"shape": "rect", "size": Vector2(190.0, 190.0)},
	"bucket_stack.png": {"shape": "circle", "size": Vector2(152.0, 152.0)},
	"monitor_top.png": {"shape": "rect", "size": Vector2(168.0, 126.0)},
	# Density assets: giants use large scales while edge details stay small.
	"giant_cereal_box.png": {"solid": true, "shape": "rect", "size": Vector2(180.0, 210.0)},
	"giant_mug.png": {"solid": true, "shape": "circle", "size": Vector2(130.0, 130.0)},
	"giant_watermelon.png": {"solid": true, "shape": "circle", "size": Vector2(140.0, 140.0)},
	"giant_fork.png": {"solid": true, "shape": "rect", "size": Vector2(60.0, 220.0)},
	"giant_basketball.png": {"solid": true, "shape": "circle", "shadow_shape": &"circle", "size": Vector2(140.0, 140.0)},
	"giant_toolbox.png": {"solid": true, "shape": "rect", "size": Vector2(200.0, 120.0)},
	"giant_paint_can.png": {"solid": true, "shape": "rect", "size": Vector2(120.0, 120.0)},
	"giant_keyboard.png": {"solid": true, "shape": "rect", "size": Vector2(220.0, 150.0)},
	"giant_monitor.png": {"solid": true, "shape": "rect", "size": Vector2(180.0, 130.0)},
	"giant_paper_stack.png": {"solid": true, "shape": "rect", "size": Vector2(170.0, 120.0)},
	"giant_pen.png": {"solid": true, "shape": "rect", "size": Vector2(40.0, 210.0)},
	"giant_toaster.png": {"solid": true, "shape": "rect", "size": Vector2(190.0, 135.0)},
	"giant_milk_carton.png": {"solid": true, "shape": "rect", "size": Vector2(125.0, 210.0)},
	"giant_hammer.png": {"solid": true, "shape": "rect", "size": Vector2(205.0, 95.0)},
	"giant_wrench.png": {"solid": true, "shape": "rect", "size": Vector2(215.0, 72.0)},
	"giant_stapler.png": {"solid": true, "shape": "rect", "size": Vector2(205.0, 105.0)},
	"giant_mouse.png": {"solid": true, "shape": "circle", "size": Vector2(150.0, 180.0)},
	"screw_small.png": {"shape": "rect", "size": Vector2(22.0, 60.0)},
	"paperclip_micro.png": {"shape": "rect", "size": Vector2(30.0, 20.0)},
}

static var LAYOUTS := {
	&"kitchen": {
		"scene": "res://scenes/tracks/kitchen_circuit.tscn",
		"root_name": "KitchenGraybox",
		"focal_fallback": "res://assets/textures/tabletop/espresso_mug.png",
		"landmark_fallbacks": ["res://assets/textures/kitchen/sponge_wet.png", "res://assets/textures/imagine/salt_shaker.png"],
		"ambient_props": ["res://assets/textures/tabletop/cereal_ring.png", "res://assets/textures/tabletop/cork.png", "res://assets/textures/tabletop/cork_cylinder.png", "res://assets/textures/tabletop/cork_disk.png", "res://assets/textures/imagine/strawberry.png", "res://assets/textures/edge_dressing/kitchen_herb_micro.png", "res://assets/textures/tabletop/biscuit.png", "res://assets/textures/tabletop/biscuit_round.png", "res://assets/textures/tabletop/cracker_square.png", "res://assets/textures/tabletop/jar_lid.png"],
		"gate_props": ["res://assets/textures/tabletop/cork.png", "res://assets/textures/tabletop/cork_disk.png", "res://assets/textures/tabletop/biscuit.png", "res://assets/textures/tabletop/cracker_square.png", "res://assets/textures/tabletop/jar_lid.png"],
		"controls": [
			Vector2(640, 370), Vector2(300, 370), Vector2(-300, 370), Vector2(-640, 370),
			Vector2(-640, 200), Vector2(-640, -200), Vector2(-640, -370), Vector2(-300, -370),
			Vector2(300, -370), Vector2(640, -370), Vector2(640, -200), Vector2(640, 200),
		],
		"floor": Color("3a332c"),
		"highlight": Color("4a4238"),
		"rim_dark": Color("3f2a22"),
		"rim_highlight": Color("ead6aa", 0.78),
		"island": Color("4a4038"),
		"asphalt": Color("2e2c28"),
		"apron": Color("3f3830"),
		"track_texture": "res://assets/textures/world_materials/kitchen_counter.png",
		"track_tile_modulate": 1.06,
		"track_world_tile_size": Vector2(1024.0, 1024.0),
		"track_opacity": 0.6,
		"floor_texture": "res://assets/textures/world_materials/kitchen_counter.png",
		"floor_tile_world_size": Vector2(1024.0, 1024.0),
		"island_material_texture": "res://assets/textures/world_materials/kitchen_board.png",
		"island_material_world_size": Vector2(768.0, 768.0),
		"opening_fraction": 0.035,
		"prop_texture": "res://assets/textures/imagine/island_plate.png",
		"prop_label": "Plate",
		"edge_texture": "res://assets/textures/kitchen/counter_edge.png",
		"island_expansion": 10.0,
		"island_fill_textures": [
			"res://assets/textures/kitchen/fork_cartoon.png",
			"res://assets/textures/kitchen/spoon_bridge.png",
			"res://assets/textures/tabletop/dinner_fork.png",
			"res://assets/textures/tabletop/teaspoon.png",
			"res://assets/textures/kitchen/cup_cartoon.png",
			"res://assets/textures/kitchen/mug_blue.png",
			"res://assets/textures/tabletop/mug_patterned.png",
			"res://assets/textures/tabletop/mug_enamel_red.png",
			"res://assets/textures/tabletop/bowl_patterned.png",
			"res://assets/textures/kitchen/cereal_tower_green.png",
			"res://assets/textures/imagine/frying_pan.png",
			"res://assets/textures/imagine/plant_small.png",
			"res://assets/textures/imagine/teacup_saucer.png",
			"res://assets/textures/imagine/salt_shaker.png",
			"res://assets/textures/imagine/mug_top.png",
		],
		"island_fill_tiny": [
			"res://assets/textures/tabletop/cork_disk.png",
			"res://assets/textures/tabletop/jar_lid.png",
			"res://assets/textures/tabletop/teaspoon.png",
			"res://assets/textures/tabletop/cracker_square.png",
		],
		"boundary_long": [
			"res://assets/textures/kitchen/ruler_plank.png",
			"res://assets/textures/track_boundary/kitchen_ruler_painted.png",
			"res://assets/textures/track_boundary/kitchen_craft_stick.png",
			"res://assets/textures/track_boundary/kitchen_chopsticks_pair.png",
			"res://assets/textures/imagine/plank_wood.png",
			"res://assets/textures/imagine/hazard_workshop_socket.png",
		],
		"generated_boundary": {
			"section": "res://assets/textures/track_boundary/kitchen_spoon_rail.png",
			"sections": [
				"res://assets/textures/kitchen/fork_cartoon.png",
				"res://assets/textures/track_boundary/kitchen_spoon_rail.png",
				"res://assets/textures/track_boundary/kitchen_chopstick_rail.png",
				"res://assets/textures/tabletop/dinner_fork.png",
				"res://assets/textures/tabletop/teaspoon.png",
				"res://assets/textures/track_boundary/kitchen_ruler_painted.png",
				"res://assets/textures/track_boundary/kitchen_craft_stick.png",
				"res://assets/textures/track_boundary/kitchen_chopsticks_pair.png",
				"res://assets/textures/track_boundary/kitchen_butter_knife.png",
				"res://assets/textures/tabletop/cork.png",
			],
			"accent": "res://assets/textures/kitchen/sponge_wet.png",
		},
		"boundary_corner": [
			"res://assets/textures/imagine/flower_pot.png",
			"res://assets/textures/imagine/barrel_wood.png",
			"res://assets/textures/imagine/plant_small.png",
		],
		"corner_giants": [
			"res://assets/textures/imagine/barrel_wood.png",
			"res://assets/textures/imagine/workshop_paint_can.png",
			"res://assets/textures/imagine/hose_coil.png",
		],
		"decals": [
			"res://assets/textures/imagine/crumb_cluster.png",
			"res://assets/textures/imagine/stain_ring.png",
			"res://assets/textures/kitchen/wet_spill.png",
			"res://assets/textures/kitchen/spill_decal.png",
			"res://assets/textures/kitchen/wood_scratch.png",
			"res://assets/textures/kitchen/water_droplet_01.png",
			"res://assets/textures/kitchen/water_droplet_02.png",
			"res://assets/textures/kitchen/cereal_scatter.png",
		],
		"ground_sections": [
			{"asset": "res://assets/textures/ground_dressing/kitchen_tablecloth_patch.png", "size": 330.0, "alpha": 0.92},
			{"asset": "res://assets/textures/ground_dressing/kitchen_dish_towel_blue.png", "size": 270.0, "alpha": 0.96},
			{"asset": "res://assets/textures/ground_dressing/kitchen_cleaning_rag_yellow.png", "size": 220.0, "alpha": 0.94},
			{"asset": "res://assets/textures/ground_dressing/kitchen_oven_mitt_red.png", "size": 205.0, "alpha": 0.96},
		],
		"edge_decor": [
			"res://assets/textures/edge_dressing/crumb_micro_01.png",
			"res://assets/textures/edge_dressing/crumb_micro_02.png",
			"res://assets/textures/edge_dressing/fiber_strand.png",
			"res://assets/textures/edge_dressing/droplet_micro.png",
			"res://assets/textures/edge_dressing/wood_grain_faint.png",
			"res://assets/textures/edge_dressing/cork_bump.png",
			"res://assets/textures/edge_dressing/kitchen_herb_micro.png",
		],
		"giants": [
			"res://assets/textures/giant_props/giant_cereal_box.png",
			"res://assets/textures/giant_props/giant_mug.png",
			"res://assets/textures/giant_props/giant_watermelon.png",
			"res://assets/textures/giant_props/giant_fork.png",
			"res://assets/textures/giant_props/giant_toaster.png",
			"res://assets/textures/giant_props/giant_milk_carton.png",
		],
		"grip_patches": [
			{"name": &"soapy spill", "grip": 0.58, "speed": 0.85, "decal": "res://assets/textures/grip_patches/soapy_spill.png"},
			{"name": &"paper scatter", "grip": 0.85, "speed": 0.78, "decal": "res://assets/textures/grip_patches/paper_scatter.png"},
			{"name": &"flour dust", "grip": 0.76, "speed": 0.74, "decal": "res://assets/textures/grip_patches/kitchen_flour_dust.png"},
			{"name": &"syrup smear", "grip": 0.52, "speed": 0.84, "decal": "res://assets/textures/grip_patches/kitchen_syrup_smear.png"},
		],
		"corridor_patterns": [
			"res://assets/textures/edge_dressing/wood_grain_faint.png",
			"res://assets/textures/edge_dressing/cork_bump.png",
			"res://assets/textures/edge_dressing/desk_pad_grid.png",
		],
		"obstacles": {
			"MugA": {"pos": Vector2(-300, 290), "r": 36.0, "tex": "res://assets/textures/imagine/kitchen_mug_hero.png"},
			"MugB": {"pos": Vector2(-60, 500), "r": 36.0, "tex": "res://assets/textures/imagine/kitchen_mug_blue.png"},
			"Apple": {"pos": Vector2(-500, 35), "r": 36.0, "tex": "res://assets/textures/kitchen/apple_cartoon.png"},
			"Lime": {"pos": Vector2(-390, 120), "r": 36.0, "tex": "res://assets/textures/kitchen/lime_cartoon.png"},
			"Cup": {"pos": Vector2(-510, 520), "r": 36.0, "tex": "res://assets/textures/kitchen/cup_cartoon.png"},
		},
	},
	&"workshop": {
		"scene": "res://scenes/tracks/workshop_workbench.tscn",
		"root_name": "WorkshopWorkbench",
		"focal_fallback": "res://assets/textures/imagine/matchbox.png",
		"landmark_fallbacks": ["res://assets/textures/imagine/screwdriver.png", "res://assets/textures/imagine/bolt.png"],
		"ambient_props": ["res://assets/textures/imagine/screw.png", "res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/screw_small.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/edge_dressing/workshop_bolt_micro.png", "res://assets/textures/edge_dressing/blade_fragment.png", "res://assets/textures/edge_dressing/staple_bit.png"],
		"gate_props": ["res://assets/textures/imagine/bolt.png", "res://assets/textures/edge_dressing/workshop_washer_micro.png", "res://assets/textures/edge_dressing/workshop_nail_micro.png", "res://assets/textures/tabletop/cork.png"],
		"controls": [
			Vector2(640, 370), Vector2(300, 370), Vector2(-300, 370), Vector2(-735, 330),
			Vector2(-735, 0), Vector2(-735, -250), Vector2(-600, -420), Vector2(-300, -470),
			Vector2(0, -480), Vector2(300, -470), Vector2(600, -420), Vector2(735, -250),
			Vector2(735, 0), Vector2(735, 370),
		],
		"floor": Color("7a5a3f"),
		"highlight": Color("8a6a4f"),
		"rim_dark": Color("3f2a22"),
		"rim_highlight": Color("d7b27c", 0.76),
		"island": Color("4a4038"),
		"asphalt": Color("2e2c28"),
		"apron": Color("5c4638"),
		"track_texture": "res://assets/textures/world_materials/workshop_bench.png",
		"track_tile_modulate": 1.06,
		"track_world_tile_size": Vector2(1280.0, 1280.0),
		"track_opacity": 0.6,
		"floor_texture": "res://assets/textures/world_materials/workshop_bench.png",
		"floor_tile_world_size": Vector2(1280.0, 1280.0),
		"island_material_texture": "res://assets/textures/world_materials/workshop_mat.png",
		"island_material_world_size": Vector2(768.0, 768.0),
		"opening_fraction": 0.035,
		"prop_texture": "res://assets/textures/imagine/island_tool_tray.png",
		"distinct_giant_assets": true,
		"prop_label": "Toolbox",
		"edge_texture": "res://assets/textures/imagine/workshop_edge_bright.png",
		"island_fill_textures": [
			"res://assets/textures/imagine/plank_wood.png",
			"res://assets/textures/imagine/workshop_paint_can.png",
			"res://assets/textures/imagine/hazard_workshop_socket.png",
			"res://assets/textures/kitchen/fork_cartoon.png",
			"res://assets/textures/kitchen/ruler_plank.png",
			"res://assets/textures/imagine/wrench.png",
			"res://assets/textures/imagine/hammer.png",
			"res://assets/textures/imagine/remote_control.png",
			"res://assets/textures/imagine/screwdriver.png",
			"res://assets/textures/imagine/tape_roll.png",
			"res://assets/textures/imagine/matchbox.png",
		],
		"island_fill_tiny": [
			"res://assets/textures/imagine/screw.png",
			"res://assets/textures/imagine/bolt.png",
			"res://assets/textures/edge_dressing/workshop_nail_micro.png",
			"res://assets/textures/edge_dressing/workshop_washer_micro.png",
			"res://assets/textures/edge_dressing/blade_fragment.png",
		],
		"boundary_long": [
			"res://assets/textures/kitchen/ruler_plank.png",
			"res://assets/textures/kitchen/spoon_bridge.png",
		],
		"generated_boundary": {
			"section": "res://assets/textures/track_boundary/workshop_paint_stirrer_rail.png",
			"sections": [
				"res://assets/textures/track_boundary/workshop_paint_stirrer_rail.png",
				"res://assets/textures/track_boundary/workshop_dowel_rail.png",
				"res://assets/textures/track_boundary/workshop_clamp_rail.png",
				"res://assets/textures/track_boundary/workshop_ruler_rail.png",
				"res://assets/textures/edge_dressing/workshop_nail_micro.png",
				"res://assets/textures/edge_dressing/workshop_bolt_micro.png",
				"res://assets/textures/edge_dressing/screw_small.png",
				"res://assets/textures/edge_dressing/blade_fragment.png",
			],
			"accent": "res://assets/textures/track_boundary/workshop_tape_corner.png",
		},
		"boundary_corner": [
			"res://assets/textures/imagine/flower_pot.png",
			"res://assets/textures/imagine/plant_small.png",
			"res://assets/textures/kitchen/cup_cartoon.png",
		],
		"corner_giants": [
			"res://assets/textures/imagine/mug_top.png",
			"res://assets/textures/imagine/teapot_top.png",
			"res://assets/textures/imagine/vase_top.png",
		],
		"decals": [
			"res://assets/textures/imagine/sawdust_patch.png",
			"res://assets/textures/imagine/oil_stain.png",
			"res://assets/textures/imagine/stain_ring.png",
			"res://assets/textures/kitchen/wood_scratch.png",
		],
		"ground_sections": [
			{"asset": "res://assets/textures/ground_dressing/workshop_dropcloth_patch.png", "size": 340.0, "alpha": 0.90},
			{"asset": "res://assets/textures/ground_dressing/workshop_shop_rag_red.png", "size": 220.0, "alpha": 0.94},
			{"asset": "res://assets/textures/ground_dressing/workshop_cardboard_scrap.png", "size": 270.0, "alpha": 0.96},
			{"asset": "res://assets/textures/ground_dressing/workshop_sandpaper_sheet.png", "size": 210.0, "alpha": 0.95},
		],
		"edge_decor": [
			"res://assets/textures/edge_dressing/screw_small.png",
			"res://assets/textures/edge_dressing/pencil_shaving.png",
			"res://assets/textures/edge_dressing/sawdust_bit.png",
			"res://assets/textures/edge_dressing/blade_fragment.png",
			"res://assets/textures/edge_dressing/staple_bit.png",
			"res://assets/textures/edge_dressing/wood_grain_faint.png",
			"res://assets/textures/edge_dressing/cork_bump.png",
			"res://assets/textures/edge_dressing/workshop_nail_micro.png",
			"res://assets/textures/edge_dressing/workshop_washer_micro.png",
			"res://assets/textures/edge_dressing/workshop_bolt_micro.png",
		],
		"giants": [
			"res://assets/textures/workshop_hero/hero_workshop_toolbox.png",
			"res://assets/textures/workshop_hero/hero_workshop_paint_can.png",
			"res://assets/textures/giant_props/giant_hammer.png",
			"res://assets/textures/giant_props/giant_wrench.png",
		],
		"grip_patches": [
			{"name": &"bench sawdust", "grip": 0.72, "speed": 0.72, "decal": "res://assets/textures/grip_patches/sawdust_patch.png"},
			{"name": &"oil slick", "grip": 0.48, "speed": 0.88, "decal": "res://assets/textures/grip_patches/oil_slick_small.png"},
			{"name": &"paint dust", "grip": 0.78, "speed": 0.74, "decal": "res://assets/textures/grip_patches/paper_scatter.png"},
			{"name": &"metal filings", "grip": 0.7, "speed": 0.72, "decal": "res://assets/textures/grip_patches/workshop_metal_filings.png"},
			{"name": &"paint smear", "grip": 0.57, "speed": 0.82, "decal": "res://assets/textures/grip_patches/workshop_paint_smear.png"},
		],
		"corridor_patterns": [
			"res://assets/textures/edge_dressing/wood_grain_faint.png",
			"res://assets/textures/edge_dressing/cork_bump.png",
		],
		"island_expansion": 10.0,
		"obstacles": {
			"CerealA": {"pos": Vector2(300, 430), "r": 38.0, "tex": "res://assets/textures/imagine/workshop_paint_can.png"},
			"MugA": {"pos": Vector2(-300, 290), "r": 36.0, "tex": "res://assets/textures/imagine/workshop_paint_can.png"},
			"MugB": {"pos": Vector2(-60, 500), "r": 36.0, "tex": "res://assets/textures/imagine/workshop_paint_can.png"},
			"Sponge": {"pos": Vector2(-180, 300), "r": 34.0, "tex": "res://assets/textures/kitchen/sponge_wet.png"},
			"Ruler": {"pos": Vector2(-60, 290), "r": 32.0, "tex": "res://assets/textures/kitchen/ruler_plank.png"},
			"Fork": {"pos": Vector2(-820, -330), "r": 34.0, "tex": "res://assets/textures/kitchen/fork_cartoon.png"},
			"Spoon": {"pos": Vector2(830, -80), "r": 36.0, "tex": "res://assets/textures/imagine/hazard_workshop_socket.png"},
			"Apple": {"pos": Vector2(-500, 35), "r": 36.0, "tex": "res://assets/textures/kitchen/apple_cartoon.png"},
			"Lime": {"pos": Vector2(-390, 120), "r": 36.0, "tex": "res://assets/textures/kitchen/lime_cartoon.png"},
			"Cup": {"pos": Vector2(-510, 520), "r": 36.0, "tex": "res://assets/textures/kitchen/cup_cartoon.png"},
			"CerealB": {"pos": Vector2(200, -60), "r": 36.0, "tex": "res://assets/textures/kitchen/cereal_tower_green.png"},
		},
		"apron_props": [
															{"pos": Vector2(-560, -260), "r": 26.0, "tex": "res://assets/textures/kitchen/apple_cartoon.png"},
			{"pos": Vector2(-450, -300), "r": 24.0, "tex": "res://assets/textures/kitchen/lime_cartoon.png"},
			{"pos": Vector2(-510, -180), "r": 22.0, "tex": "res://assets/textures/kitchen/sponge_wet.png"},
			{"pos": Vector2(120, -520), "r": 30.0, "tex": "res://assets/textures/imagine/hazard_workshop_socket.png"},
			{"pos": Vector2(260, -560), "r": 26.0, "tex": "res://assets/textures/imagine/workshop_paint_can.png"},
		],
	},
	&"office": {
		"scene": "res://scenes/tracks/office_desk.tscn",
		"root_name": "OfficeDesk",
		"focal_fallback": "res://assets/textures/tabletop/eraser.png",
		"landmark_fallbacks": ["res://assets/textures/imagine/stapler_top.png", "res://assets/textures/imagine/remote_control.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png"],
		"ambient_props": ["res://assets/textures/imagine/paperclip.png", "res://assets/textures/edge_dressing/paperclip_micro.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/tabletop/eraser.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png", "res://assets/textures/edge_dressing/office_push_pin_micro.png", "res://assets/textures/edge_dressing/office_pen_cap_micro.png", "res://assets/textures/edge_dressing/staple_bit.png", "res://assets/textures/edge_dressing/pencil_shaving.png"],
		"gate_props": ["res://assets/textures/tabletop/eraser.png", "res://assets/textures/office_hero/hero_office_keycap.png", "res://assets/textures/edge_dressing/office_binder_clip_micro.png", "res://assets/textures/edge_dressing/office_push_pin_micro.png"],
		"controls": [
			Vector2(640, 370), Vector2(300, 370), Vector2(-300, 370), Vector2(-400, 340),
			Vector2(-700, 260), Vector2(-820, 215), Vector2(-750, 180), Vector2(-600, 112),
			Vector2(-400, 22), Vector2(-200, -67), Vector2(0, -157), Vector2(200, -246),
			Vector2(400, -336), Vector2(600, -420), Vector2(735, -300), Vector2(735, 0),
			Vector2(735, 370),
		],
		"floor": Color("5a6170"),
		"highlight": Color("6a7180"),
		"rim_dark": Color("30343d"),
		"rim_highlight": Color("c4ccd2", 0.74),
		"island": Color("4a505c"),
		"asphalt": Color("272b31"),
		"apron": Color("4a5060"),
		"track_texture": "res://assets/textures/world_materials/office_desk.png",
		"track_tile_modulate": 1.05,
		"track_world_tile_size": Vector2(1024.0, 1024.0),
		"track_opacity": 0.6,
		"floor_texture": "res://assets/textures/world_materials/office_desk.png",
		"floor_tile_world_size": Vector2(1024.0, 1024.0),
		"island_material_texture": "res://assets/textures/world_materials/office_pad.png",
		"island_material_world_size": Vector2(768.0, 768.0),
		"opening_fraction": 0.035,
		"prop_texture": "res://assets/textures/imagine/island_keyboard.png",
		"distinct_giant_assets": true,
		"prop_label": "Keyboard",
		"edge_texture": "res://assets/textures/world_materials/office_pad.png",
		"island_fill_textures": [
			"res://assets/textures/imagine/book_top.png",
			"res://assets/textures/imagine/plank_wood.png",
			"res://assets/textures/imagine/office_keycap.png",
			"res://assets/textures/kitchen/ruler_plank.png",
			"res://assets/textures/imagine/remote_control.png",
			"res://assets/textures/imagine/plant_small.png",
			"res://assets/textures/imagine/stapler_top.png",
			"res://assets/textures/imagine/pencil.png",
			"res://assets/textures/imagine/crayons.png",
			"res://assets/textures/imagine/scissors_top.png",
			"res://assets/textures/imagine/tape_roll.png",
		],
		"island_fill_tiny": [
			"res://assets/textures/imagine/paperclip.png",
			"res://assets/textures/office_hero/hero_office_keycap.png",
			"res://assets/textures/tabletop/eraser.png",
			"res://assets/textures/edge_dressing/office_binder_clip_micro.png",
			"res://assets/textures/edge_dressing/office_pen_cap_micro.png",
		],
		"boundary_long": [
			"res://assets/textures/kitchen/ruler_plank.png",
			"res://assets/textures/imagine/office_keycap.png",
			"res://assets/textures/imagine/pencil.png",
		],
		"generated_boundary": {
			"section": "res://assets/textures/track_boundary/office_pencil_rail.png",
			"sections": [
				"res://assets/textures/track_boundary/office_pencil_rail.png",
				"res://assets/textures/track_boundary/office_ruler_rail.png",
				"res://assets/textures/track_boundary/office_pen_rail.png",
				"res://assets/textures/track_boundary/office_book_spine_rail.png",
				"res://assets/textures/tabletop/eraser.png",
				"res://assets/textures/edge_dressing/office_binder_clip_micro.png",
				"res://assets/textures/edge_dressing/office_push_pin_micro.png",
				"res://assets/textures/edge_dressing/staple_bit.png",
			],
			"accent": "res://assets/textures/track_boundary/office_sticky_corner.png",
		},
		"boundary_corner": [
			"res://assets/textures/imagine/flower_pot.png",
			"res://assets/textures/imagine/barrel_wood.png",
			"res://assets/textures/imagine/plant_small.png",
		],
		"corner_giants": [
			"res://assets/textures/imagine/lamp_desk.png",
			"res://assets/textures/imagine/tape_roll.png",
			"res://assets/textures/imagine/mug_top.png",
		],
		"decals": [
			"res://assets/textures/imagine/paper_sheet.png",
			"res://assets/textures/imagine/stain_ring.png",
			"res://assets/textures/imagine/crumb_cluster.png",
		],
		"ground_sections": [
			{"asset": "res://assets/textures/ground_dressing/office_desk_pad_patch.png", "size": 330.0, "alpha": 0.88},
			{"asset": "res://assets/textures/ground_dressing/office_envelope_stack.png", "size": 255.0, "alpha": 0.96},
			{"asset": "res://assets/textures/ground_dressing/office_sticky_notes.png", "size": 220.0, "alpha": 0.96},
			{"asset": "res://assets/textures/ground_dressing/office_notepad_page.png", "size": 245.0, "alpha": 0.96},
		],
		"edge_decor": [
			"res://assets/textures/edge_dressing/paperclip_micro.png",
			"res://assets/textures/edge_dressing/staple_bit.png",
			"res://assets/textures/edge_dressing/fiber_strand.png",
			"res://assets/textures/edge_dressing/droplet_micro.png",
			"res://assets/textures/edge_dressing/screw_small.png",
			"res://assets/textures/edge_dressing/desk_pad_grid.png",
			"res://assets/textures/edge_dressing/cork_bump.png",
			"res://assets/textures/edge_dressing/office_binder_clip_micro.png",
			"res://assets/textures/edge_dressing/office_push_pin_micro.png",
			"res://assets/textures/edge_dressing/office_pen_cap_micro.png",
		],
		"giants": [
			"res://assets/textures/office_hero/hero_office_keyboard.png",
			"res://assets/textures/office_hero/hero_office_notebook.png",
			"res://assets/textures/giant_props/giant_monitor.png",
			"res://assets/textures/giant_props/giant_paper_stack.png",
			"res://assets/textures/giant_props/giant_pen.png",
			"res://assets/textures/giant_props/giant_stapler.png",
			"res://assets/textures/giant_props/giant_mouse.png",
		],
		"grip_patches": [
			{"name": &"papers", "grip": 0.82, "speed": 0.76, "decal": "res://assets/textures/grip_patches/paper_scatter.png"},
			{"name": &"coffee ring", "grip": 0.55, "speed": 0.85, "decal": "res://assets/textures/grip_patches/coffee_ring.png"},
			{"name": &"soapy desk", "grip": 0.62, "speed": 0.82, "decal": "res://assets/textures/grip_patches/soapy_spill.png"},
			{"name": &"eraser dust", "grip": 0.78, "speed": 0.75, "decal": "res://assets/textures/grip_patches/office_eraser_dust.png"},
			{"name": &"ink blot", "grip": 0.5, "speed": 0.83, "decal": "res://assets/textures/grip_patches/office_ink_blot.png"},
		],
		"corridor_patterns": [
			"res://assets/textures/edge_dressing/desk_pad_grid.png",
			"res://assets/textures/edge_dressing/wood_grain_faint.png",
		],
		"island_expansion": 4.0,
		"gate_fractions": [0.0, 0.125, 0.25, 0.43, 0.55, 0.67, 0.72, 0.74],
		"obstacles": {
			"CerealA": {"pos": Vector2(300, 430), "r": 38.0, "tex": "res://assets/textures/imagine/office_keycap.png"},
			"MugA": {"pos": Vector2(-300, 500), "r": 36.0, "tex": "res://assets/textures/imagine/kitchen_mug_hero.png"},
			"MugB": {"pos": Vector2(-60, 520), "r": 36.0, "tex": "res://assets/textures/imagine/kitchen_mug_blue.png"},
			"Sponge": {"pos": Vector2(-180, 300), "r": 34.0, "tex": "res://assets/textures/kitchen/sponge_wet.png"},
			"Ruler": {"pos": Vector2(-60, 200), "r": 32.0, "tex": "res://assets/textures/kitchen/ruler_plank.png"},
			"Fork": {"pos": Vector2(-820, -330), "r": 34.0, "tex": "res://assets/textures/kitchen/fork_cartoon.png"},
			"Remote": {"pos": Vector2(830, 120), "r": 36.0, "tex": "res://assets/textures/imagine/remote_control.png"},
			"Apple": {"pos": Vector2(-470, 60), "r": 36.0, "tex": "res://assets/textures/kitchen/apple_cartoon.png"},
			"Lime": {"pos": Vector2(-410, 170), "r": 36.0, "tex": "res://assets/textures/kitchen/lime_cartoon.png"},
			"Cup": {"pos": Vector2(-560, 540), "r": 36.0, "tex": "res://assets/textures/kitchen/cup_cartoon.png"},
			"CerealB": {"pos": Vector2(200, -60), "r": 36.0, "tex": "res://assets/textures/imagine/office_keycap.png"},
		},
		"apron_props": [
			{"pos": Vector2(-300, -340), "r": 24.0, "tex": "res://assets/textures/imagine/office_keycap.png"},
			{"pos": Vector2(-500, -420), "r": 22.0, "tex": "res://assets/textures/imagine/office_keycap.png"},
			{"pos": Vector2(-180, -480), "r": 26.0, "tex": "res://assets/textures/kitchen/sponge_wet.png"},
			{"pos": Vector2(-420, -560), "r": 24.0, "tex": "res://assets/textures/kitchen/lime_cartoon.png"},
			{"pos": Vector2(180, -560), "r": 22.0, "tex": "res://assets/textures/imagine/office_keycap.png"},
		],
	},
}


static func catalog() -> Dictionary:
	for filename: String in PROP_SCALE.scenery_lengths:
		var entry: Dictionary = PROP_SHAPES.get(filename, {}).duplicate()
		entry["shadow_shape"] = entry.get("shadow_shape", &"circle" if StringName(entry.get("shape", "convex")) == &"circle" else &"rect")
		entry["size"] = Vector2.ONE * PROP_SCALE.length_for(filename, 0.0)
		entry["solid"] = true
		entry["shape"] = "convex"
		PROP_SHAPES[filename] = entry
		ASSET_FOOTPRINT_OVERRIDES[filename] = {"kind": &"convex", "no_rotation": true}
	return {
		"generated_obstacle_types": GENERATED_OBSTACLE_TYPES,
		"solid_edge_shapes": SOLID_EDGE_SHAPES,
		"flat_edge_assets": FLAT_EDGE_ASSETS,
		"asset_footprint_overrides": ASSET_FOOTPRINT_OVERRIDES,
		"room_shapes": ROOM_SHAPES,
		"base_room_shapes": BASE_ROOM_SHAPES,
		"island_vignettes": ISLAND_VIGNETTES,
		"room_compositions": ROOM_COMPOSITIONS,
		"story_kits": STORY_KITS,
		"prop_shapes": PROP_SHAPES,
		"layouts": LAYOUTS,
	}
