extends RefCounted

const GROUP_ORDER := [
	&"engine_loop",
	&"countdown",
	&"go",
	&"ui_move",
	&"ui_confirm",
	&"drift",
	&"boost",
	&"impact",
	&"hazard_warning",
]

const GROUPS := {
	&"engine_loop": {
		"display_name": "ENGINE LOOP",
		"prompt": "Does the loop read as a tiny vehicle, stay clear across pitch changes, and avoid fatigue or a noticeable seam?",
		"one_shot_cap_seconds": 0.0,
		"candidates": [
			{
				"variant": "A",
				"label": "Circular motor",
				"path": "res://prototypes/audio_audition/candidates/engine_loop_a.ogg",
				"pack_name": "Kenney Sci-Fi Sounds 1.0",
				"pack_filename": "kenney_sci-fi-sounds.zip",
				"pack_sha256": "119340f351a5098ad814f78719438c0da355a9ce8a4c8a3af6a8d48aa3d49e04",
				"source_page": "https://kenney.nl/assets/sci-fi-sounds",
				"source_files": ["Audio/engineCircular_000.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; full 5.000 s retained.",
				"expected_duration_seconds": 5.000,
				"loop": true,
			},
			{
				"variant": "B",
				"label": "Small space motor",
				"path": "res://prototypes/audio_audition/candidates/engine_loop_b.ogg",
				"pack_name": "Kenney Sci-Fi Sounds 1.0",
				"pack_filename": "kenney_sci-fi-sounds.zip",
				"pack_sha256": "119340f351a5098ad814f78719438c0da355a9ce8a4c8a3af6a8d48aa3d49e04",
				"source_page": "https://kenney.nl/assets/sci-fi-sounds",
				"source_files": ["Audio/spaceEngineSmall_000.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; full 5.000 s retained.",
				"expected_duration_seconds": 5.000,
				"loop": true,
			},
		],
	},
	&"countdown": {
		"display_name": "COUNTDOWN",
		"prompt": "Is the pip immediate and timing-readable when repeated three times, without turning shrill?",
		"one_shot_cap_seconds": 0.75,
		"candidates": [
			{
				"variant": "A",
				"label": "Select pip 003",
				"path": "res://prototypes/audio_audition/candidates/countdown_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/select_003.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.383,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Select pip 004",
				"path": "res://prototypes/audio_audition/candidates/countdown_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/select_004.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.383,
				"loop": false,
			},
		],
	},
	&"go": {
		"display_name": "GO",
		"prompt": "Does this feel brighter and more decisive than countdown while leaving room for engine launch?",
		"one_shot_cap_seconds": 0.75,
		"candidates": [
			{
				"variant": "A",
				"label": "Confirmation 002",
				"path": "res://prototypes/audio_audition/candidates/go_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/confirmation_002.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.539,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Confirmation 003",
				"path": "res://prototypes/audio_audition/candidates/go_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/confirmation_003.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.322,
				"loop": false,
			},
		],
	},
	&"ui_move": {
		"display_name": "UI MOVE",
		"prompt": "Can this survive frequent focus movement at a restrained level without piercing or mimicking confirm?",
		"one_shot_cap_seconds": 0.25,
		"candidates": [
			{
				"variant": "A",
				"label": "Tick 004",
				"path": "res://prototypes/audio_audition/candidates/ui_move_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/tick_004.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.058,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Select 001",
				"path": "res://prototypes/audio_audition/candidates/ui_move_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/select_001.ogg"],
				"transformation": "Stereo source downmixed to mono; resampled to 48 kHz; -6 dB gain to contain Vorbis transient overshoot; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.043,
				"loop": false,
			},
		],
	},
	&"ui_confirm": {
		"display_name": "UI CONFIRM",
		"prompt": "Is this positive and distinct from focus movement without becoming a notification jingle?",
		"one_shot_cap_seconds": 0.75,
		"candidates": [
			{
				"variant": "A",
				"label": "Confirmation 001",
				"path": "res://prototypes/audio_audition/candidates/ui_confirm_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/confirmation_001.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.290,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Confirmation 004",
				"path": "res://prototypes/audio_audition/candidates/ui_confirm_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/confirmation_004.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.490,
				"loop": false,
			},
		],
	},
	&"drift": {
		"display_name": "DRIFT",
		"prompt": "Does the scratch communicate controllable tire scrub rather than broadband hiss or damage?",
		"one_shot_cap_seconds": 0.75,
		"candidates": [
			{
				"variant": "A",
				"label": "Scratch 004",
				"path": "res://prototypes/audio_audition/candidates/drift_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/scratch_004.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; natural 0.325 s tail retained.",
				"expected_duration_seconds": 0.325,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Scratch 005",
				"path": "res://prototypes/audio_audition/candidates/drift_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/scratch_005.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; natural 0.325 s tail retained.",
				"expected_duration_seconds": 0.325,
				"loop": false,
			},
		],
	},
	&"boost": {
		"display_name": "BOOST",
		"prompt": "Is the burst compact, energetic, and toy-scale without masking the engine or reading as a space weapon?",
		"one_shot_cap_seconds": 1.0,
		"candidates": [
			{
				"variant": "A",
				"label": "Thruster 000 extract",
				"path": "res://prototypes/audio_audition/candidates/boost_a.ogg",
				"pack_name": "Kenney Sci-Fi Sounds 1.0",
				"pack_filename": "kenney_sci-fi-sounds.zip",
				"pack_sha256": "119340f351a5098ad814f78719438c0da355a9ce8a4c8a3af6a8d48aa3d49e04",
				"source_page": "https://kenney.nl/assets/sci-fi-sounds",
				"source_files": ["Audio/thrusterFire_000.ogg"],
				"transformation": "First 0.850 s; 5 ms fade-in; 150 ms fade-out from 0.700 s; mono 48 kHz; -1 dB gain; Vorbis q5.",
				"expected_duration_seconds": 0.850,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Thruster 002 extract",
				"path": "res://prototypes/audio_audition/candidates/boost_b.ogg",
				"pack_name": "Kenney Sci-Fi Sounds 1.0",
				"pack_filename": "kenney_sci-fi-sounds.zip",
				"pack_sha256": "119340f351a5098ad814f78719438c0da355a9ce8a4c8a3af6a8d48aa3d49e04",
				"source_page": "https://kenney.nl/assets/sci-fi-sounds",
				"source_files": ["Audio/thrusterFire_002.ogg"],
				"transformation": "First 0.900 s; 5 ms fade-in; 180 ms fade-out from 0.720 s; mono 48 kHz; -1 dB gain; Vorbis q5.",
				"expected_duration_seconds": 0.890,
				"loop": false,
			},
		],
	},
	&"impact": {
		"display_name": "IMPACT",
		"prompt": "Does the layered hit suggest a restrained toy-body bump, with crisp contact and no cinematic weight?",
		"one_shot_cap_seconds": 0.6,
		"candidates": [
			{
				"variant": "A",
				"label": "Tin + generic body",
				"path": "res://prototypes/audio_audition/candidates/impact_a.ogg",
				"pack_name": "Kenney Impact Sounds 1.0",
				"pack_filename": "kenney_impact-sounds.zip",
				"pack_sha256": "029d734af1582474edf3a694d1b0cebc97c1c152f2f39fa34d4c2bafc5de77f8",
				"source_page": "https://kenney.nl/assets/impact-sounds",
				"source_files": ["Audio/impactTin_medium_000.ogg", "Audio/impactGeneric_light_000.ogg"],
				"transformation": "Mono 48 kHz mix: tin at 0.55 gain plus generic at 0.35 gain delayed 12 ms; unnormalized amix; 45 ms fade-out from 0.130 s; Vorbis q5.",
				"expected_duration_seconds": 0.176,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Metal + soft body",
				"path": "res://prototypes/audio_audition/candidates/impact_b.ogg",
				"pack_name": "Kenney Impact Sounds 1.0",
				"pack_filename": "kenney_impact-sounds.zip",
				"pack_sha256": "029d734af1582474edf3a694d1b0cebc97c1c152f2f39fa34d4c2bafc5de77f8",
				"source_page": "https://kenney.nl/assets/impact-sounds",
				"source_files": ["Audio/impactMetal_light_002.ogg", "Audio/impactSoft_medium_002.ogg"],
				"transformation": "Mono 48 kHz mix: metal at 0.50 gain plus soft body at 0.38 gain delayed 16 ms; unnormalized amix; 45 ms fade-out from 0.190 s; Vorbis q5.",
				"expected_duration_seconds": 0.236,
				"loop": false,
			},
		],
	},
	&"hazard_warning": {
		"display_name": "HAZARD WARNING",
		"prompt": "Is the warning unmistakable under motion while remaining brief enough to avoid alarm fatigue?",
		"one_shot_cap_seconds": 0.75,
		"candidates": [
			{
				"variant": "A",
				"label": "Error 003",
				"path": "res://prototypes/audio_audition/candidates/hazard_warning_a.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/error_003.ogg"],
				"transformation": "Stereo source downmixed to mono; resampled to 48 kHz; -6 dB gain to contain Vorbis transient overshoot; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.533,
				"loop": false,
			},
			{
				"variant": "B",
				"label": "Error 005",
				"path": "res://prototypes/audio_audition/candidates/hazard_warning_b.ogg",
				"pack_name": "Kenney Interface Sounds 1.0",
				"pack_filename": "kenney_interface-sounds.zip",
				"pack_sha256": "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232",
				"source_page": "https://kenney.nl/assets/interface-sounds",
				"source_files": ["Audio/error_005.ogg"],
				"transformation": "Mono source; resampled to 48 kHz; -1 dB gain; Vorbis q5; no trim or dynamics processing.",
				"expected_duration_seconds": 0.500,
				"loop": false,
			},
		],
	},
}
